version: 2
before:
  hooks:
    - go mod tidy
builds:
  - id: "argonap"
    main: ./cmd/argonap
    binary: argonap
    ldflags:
      - -X main.version={{.Version}}
changelog:
  disable: true
dockers:
  - image_templates:
    - "ghcr.io/ivanklee86/argonap"
