# https://taskfile.dev
version: '3'

includes:
  go: ./tasks/go.yaml
  k8s: ./tasks/k8s.yaml
  argocd: ./tasks/argocd.yaml

tasks:
  default:
    cmds:
      - task: go:fmt
      - task: go:lint
      - task: go:test
