# https://taskfile.dev
version: '3'

includes:
  go: ./tasks/go.yaml
  k8s: ./tasks/k8s.yaml
  argocd: ./tasks/argocd.yaml
  octanap: ./tasks/octanap.yaml

dotenv: ['.env']

tasks:
  default:
    cmds:
      - task: go:fmt
      - task: go:lint
      - task: go:build
      - task: go:test

  services:
    cmds:
      - task: k8s:start
      - task: argocd:healthcheck
      - task: argocd:token
