# https://taskfile.dev

version: '3'

env:
  ARGONAP_SERVER_ADDRESS: localhost:8080
  ARGONAP_INSECURE: true

tasks:
  clear:
    desc: "Test that argonap can clear syncWindows."
    cmds:
      - ./bin/argonap clear --auth-token ${ARGOCD_TOKEN}
  
  set:
    desc: "Set syncWindows."
    cmds:
      - ./bin/argonap set --auth-token ${ARGOCD_TOKEN} --file ./integration/exampleSyncWindows.json
