# https://taskfile.dev

version: '3'

vars:
  CLUSTER_NAME: local

tasks:
  start:
    desc: "Start :allthethings:!"
    cmds:
      - task: cluster:create
      - task: bootstrap

  cluster:create:
    desc: "Create k3d cluster."
    cmds:
      - k3d cluster create {{.CLUSTER_NAME}} --config ./k3d-config.yaml
      - kubectl get nodes

  cluster:delete:
    desc: "Clean up k3d cluster."
    cmds:
      - k3d cluster delete {{.CLUSTER_NAME}}
  
  cluster:configs:
    desc: "Get k3d cluster config."
    cmds:
      - mkdir ~/.kube || true
      - k3d kubeconfig get {{.CLUSTER_NAME}} > ~/.kube/config

  helm:update:
    desc: Update helm dependencies.
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - helm dep update

  helm:template:
    desc: Update helm dependencies.
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - task: helm:update
      - helm template . >> manifests.yaml

  bootstrap:
    desc: "Bootstrap k8s apps."
    cmds:
      - helm install argocd kubernetes/argocd --namespace argocd --create-namespace 
